version: '3'
services:
  python_app1:
    build: ./app1
    ports: 
     - 5001:5000 
    volumes:
     - json-data:/app
  python_app2:
    build: ./app2
    ports:
     - 5002:5000
    volumes:
     - json-data:/app
    depends_on:
      - python_app1
volumes:
  json-data:
    driver: local